#!/bin/sh

TEX=`find . -name "*.tex" | grep -v "^./latex" | sed "s/^.\///g"`

mkdir -p latex/
cp *.bib *.sty *.sed latex/
cd latex
for k in ${TEX}; do
  mkdir -p `dirname "$k"`
  cp ../"$k" `dirname "$k"`
  sed -f rules.sed -i ./"$k"
  echo "$k" "sedded"
done
latexmk -bibtex -pdf -e '$pdflatex=q/xelatex --shell-espace %O %S/' thesis.tex && \
cd ..
